apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 10m
    successCondition: result < 0.000001
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1617-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(
            sum(rate(container_cpu_usage_seconds_total{namespace="master"}[10m])) /
            sum(machine_cpu_cores) * 100
          )