apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    name: dwk-project-frontend-dep
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dwk-project-frontend
    strategy:
        canary:
            steps:
            - setWeight: 50
            - analysis:
                templates:
                - templateName: cpu-usage
    template:
        metadata:
            labels:
                app: dwk-project-frontend
        spec:
            containers:
                - name: dwk-project
                  image: PROJECT/FRONTEND_IMAGE
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 80
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 80
                    initialDelaySeconds: 5
                    periodSeconds: 5
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 80
                    initialDelaySeconds: 20
                    periodSeconds: 5
                  resources:
                    limits:
                        cpu: "100m"
                        memory: "100Mi"