apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: project
  name: dwk-project-ingress
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            service:
                name: dwk-project-frontend-svc
                port:
                number: 2345
        - path: /images
          backend:
            service:
                name: dwk-project-images-svc
                port:
                number: 2345
        - path: /todos
          backend:
            service:
                name: dwk-project-todos-svc
                port:
                number: 2345
