apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dwk-project-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: dwk-project-frontend-svc
            servicePort: 2345
        - path: /images
          backend:
            serviceName: dwk-project-images-svc
            servicePort: 2345
        - path: /todos
          backend:
            serviceName: dwk-project-todos-svc
            servicePort: 2345
