apiVersion: v1
kind: Service
metadata:
    name: dwk-project-frontend-svc
spec:
    type: NodePort 
    selector:
        app: dwk-project-frontend
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000