apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- main-application/manifests/deployment.yaml
- main-application/manifests/configmap.yaml
- main-application/manifests/persistentvolumeclaim.yaml
- main-application/manifests/service.yaml
- pingpong/manifests/deployment.yaml
- pingpong/manifests/service.yaml
- project-frontend/manifests/deployment.yaml
- project-frontend/manifests/service.yaml
- project-frontend/manifests/ingress.yaml
- project-images/manifests/deployment.yaml
- project-images/manifests/service.yaml
- project-images/manifests/persistentvolumeclaim.yaml
- project-todos/manifests/postgrespvc.yaml
- project-todos/manifests/postgresstatefulset.yaml
- project-todos/manifests/postgressvc.yaml
- project-todos/manifests/deployment.yaml
- project-todos/manifests/service.yaml
- project-todos/daily_todo/manifests/cronjob.yaml

images:
- name: MAIN_APPLICATION/READER_IMAGE
  newName: volepp/dwk-main-application-reader
  newTag: v0.3.2
- name: MAIN_APPLICATION/GENERATOR_IMAGE
  newName: volepp/dwk-main-application-generator
  newTag: v0.1.2
- name: MAIN_APPLICATION/PINGPONG_IMAGE
  newName: volepp/dwk-pingpong
  newTag: v0.3.2
- name: PROJECT/FRONTEND_IMAGE
  newName: volepp/dwk-project-frontend
  newTag: v1.4.2
- name: PROJECT/IMAGES_IMAGE
  newName: volepp/dwk-project-images
  newTag: v1.4.2
- name: PROJECT/TODOS_IMAGE
  newName: volepp/dwk-project-todos
  newTag: v1.4.2