apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/sealeddiscordtoken.yaml
- project-frontend/manifests/deployment.yaml
- project-frontend/manifests/service.yaml
- project-frontend/manifests/ingress.yaml
- project-frontend/manifests/analysistemplate.yaml
- project-images/manifests/deployment.yaml
- project-images/manifests/service.yaml
- project-images/manifests/persistentvolumeclaim.yaml
- project-todos/manifests/postgrespvc.yaml
- project-todos/manifests/postgresstatefulset.yaml
- project-todos/manifests/postgressvc.yaml
- project-todos/manifests/deployment.yaml
- project-todos/manifests/service.yaml
- project-todos/daily_todo/manifests/cronjob.yaml
- project-todos/manifests/sealedsecret.yaml
- project-broadcaster/manifests/deployment.yaml

images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: volepp/dwk-project-broadcaster
  newTag: 54b30bcb84e71e90ed2677810ec576e1ac55da4b
- name: PROJECT/FRONTEND_IMAGE
  newName: volepp/dwk-project-frontend
  newTag: 54b30bcb84e71e90ed2677810ec576e1ac55da4b
- name: PROJECT/IMAGES_IMAGE
  newName: volepp/dwk-project-images
  newTag: 54b30bcb84e71e90ed2677810ec576e1ac55da4b
- name: PROJECT/TODOS_IMAGE
  newName: volepp/dwk-project-todos
  newTag: 54b30bcb84e71e90ed2677810ec576e1ac55da4b
