apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummy-site-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dummy-site-controller-role
subjects:
- kind: ServiceAccount
  name: dummy-site-account
  namespace: default