apiVersion: apps/v1
kind: Deployment
metadata:
    name: dwk-pingpong-dep
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dwk-pingpong
    template:
        metadata:
            labels:
                app: dwk-pingpong
        spec:
            volumes:
              - name: shared-volume
                persistentVolumeClaim:
                    claimName: dwk-main-application-claim
            containers:
                - name: dwk-pingpong
                  image: volepp/dwk-pingpong:v0.2.1
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: shared-volume
                      mountPath: /usr/src/app/files
