apiVersion: apps/v1
kind: Deployment
metadata:
    name: dwk-pingpong-dep
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dwk-pingpong
    template:
        metadata:
            labels:
                app: dwk-pingpong
        spec:
            containers:
                - name: dwk-pingpong
                  image: MAIN_APPLICATION/PINGPONG_IMAGE
                  imagePullPolicy: Always
                  env:
                    - name: POSTGRES_DB
                      valueFrom:
                        secretKeyRef:
                            name: dwk-postgres-credentials
                            key: POSTGRES_DB
                    - name: POSTGRES_USER
                      valueFrom:
                        secretKeyRef:
                            name: dwk-postgres-credentials
                            key: POSTGRES_USER
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: dwk-postgres-credentials
                            key: POSTGRES_PASSWORD
