apiVersion: v1
kind: Service
metadata:
  namespace: main-application
  name: dwk-pingpong-svc
spec:
  type: LoadBalancer
  selector:
    app: dwk-pingpong
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000