apiVersion: v1
kind: Service
metadata:
  namespace: main-application
  name: dwk-postgres-svc
  labels:
    app: dwk-postgres
spec:  
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: dwk-postgres
