apiVersion: v1
kind: Service
metadata:
    name: dwk-pingpong-svc
spec:
    type: NodePort 
    selector:
        app: dwk-pingpong
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
