apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    name: dwk-project-broadcaster-dep
spec:
    replicas: 6
    selector:
        matchLabels:
            app: dwk-project-broadcaster
    strategy:
        canary:
            steps:
            - setWeight: 50
            - analysis:
                templates:
                - templateName: cpu-usage
    template:
        metadata:
            labels:
                app: dwk-project-broadcaster
        spec:
            containers:
                - name: dwk-project-broadcaster
                  image: PROJECT/BROADCASTER_IMAGE
                  imagePullPolicy: Always
                  env:
                    - name: NATS_NAME
                      value: dwk-nats
                    - name: NAMESPACE
                      valueFrom:
                        configMapKeyRef:
                          name: namespace-config
                          key: namespace
                    - name: DISCORD_TOKEN
                      valueFrom:
                        secretKeyRef:
                            name: dwk-discord-token
                            key: DISCORD_TOKEN
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 3000
                    initialDelaySeconds: 20
                    periodSeconds: 5
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 5
                  resources:
                    limits:
                      cpu: "100m"
                      memory: "75Mi"
