apiVersion: apps/v1
kind: Deployment
metadata:
    name: dwk-project-todos
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dwk-project-todos
    template:
        metadata:
            labels:
                app: dwk-project-todos
        spec:
            containers:
                - name: dwk-project-todos
                  image: volepp/dwk-project-todos:v1.0
                  imagePullPolicy: Always
