apiVersion: v1
kind: Service
metadata:
    name: dwk-project-todos-svc
spec:
    type: NodePort 
    selector:
        app: dwk-project-todos
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
