apiVersion: apps/v1
kind: Deployment
metadata:
    name: dwk-project-images-dep
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dwk-project-images
    template:
        metadata:
            labels:
                app: dwk-project-images
        spec:
            volumes:
              - name: shared-volume
                persistentVolumeClaim:
                    claimName: dwk-project-images-pvc
            containers:
                - name: dwk-project
                  image: PROJECT/IMAGES_IMAGE
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: shared-volume
                      mountPath: /app/public
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 3000
                    initialDelaySeconds: 5
                    periodSeconds: 5
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 3000
                    initialDelaySeconds: 10
                    periodSeconds: 5
                  resources:
                    limits:
                      cpu: "100m"
                      memory: "50Mi"

