apiVersion: apps/v1
kind: Deployment
metadata:
    name: dwk-project-images-dep
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dwk-project-images
    template:
        metadata:
            labels:
                app: dwk-project-images
        spec:
            volumes:
              - name: shared-volume
                persistentVolumeClaim:
                    claimName: dwk-project-pvc
            containers:
                - name: dwk-project
                  image: PROJECT/IMAGES_IMAGE
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: shared-volume
                      mountPath: /usr/src/app/public
                  readinessProbe:
                    tcpSocket:
                        port: 3000
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  livenessProbe:
                    tcpSocket:
                        port: 3000
                    initialDelaySeconds: 15
                    periodSeconds: 20
                    

