apiVersion: v1
kind: Service
metadata:
    name: dwk-project-images-svc
spec:
    type: NodePort 
    selector:
        app: dwk-project-images
    ports:
        - port: 2345
          protocol: TCP
          targetPort: 3000
