apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-main-application-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-main-application
  template:
    metadata:
      labels:
        app: dwk-main-application
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
              claimName: dwk-main-application-pvc
      containers:
        - name: dwk-main-application-generator
          image: MAIN_APPLICATION/GENERATOR_IMAGE
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
        - name: dwk-main-application-reader
          image: MAIN_APPLICATION/READER_IMAGE
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
              readOnly: true
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: main-application-configmap
                  key: message
