apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dwk-main-application-ingress
spec:
  rules:
    - http:
        paths:
        - path: /status
          backend:
            serviceName: dwk-main-application-svc
            servicePort: 80
        - path: /pingpong
          backend:
            serviceName: dwk-pingpong-svc
            servicePort: 80
