apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: main-application
  name: dwk-main-application-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: dwk-main-application-svc
            servicePort: 80
        - path: /pingpong
          backend:
            serviceName: dwk-pingpong-svc
            servicePort: 80
