apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: dwk-main-application-claim
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
