apiVersion: v1
kind: Service
metadata:  
    namespace: main-application
    name: dwk-main-application-svc
spec:
    type: NodePort
    selector:
        app: dwk-main-application
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
