apiVersion: v1
kind: Service
metadata:
    name: dwk-main-application-svc
spec:
    type: ClusterIP
    selector:
        app: dwk-main-application
    ports:
        - port: 2345
          protocol: TCP
          targetPort: 3000
