name: Release project with GitOps

on:
  push:
    branches:
      - master
    paths:
      - "kustomization.yaml"
      - "project-frontend/**"
      - "project-broadcaster/**"
      - "project-images/**"
      - "project-todos/**"
      - ".github/workflows/gitops.yaml"

env:
  FRONTEND_IMAGE: dwk-project-frontend
  IMAGES_IMAGE: dwk-project-images
  TODOS_IMAGE: dwk-project-todos
  BROADCASTER_IMAGE: dwk-project-broadcaster

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build and push images
    - name: Create images' names and tags
      run: |
        echo "FRONTEND_IMAGE_WITH_TAG=volepp/$FRONTEND_IMAGE:${{ github.sha }}" >> $GITHUB_ENV
        echo "IMAGES_IMAGE_WITH_TAG=volepp/$IMAGES_IMAGE:${{ github.sha }}" >> $GITHUB_ENV
        echo "TODOS_IMAGE_WITH_TAG=volepp/$TODOS_IMAGE:${{ github.sha }}" >> $GITHUB_ENV
        echo "BROADCASTER_IMAGE_WITH_TAG=volepp/$BROADCASTER_IMAGE:${{ github.sha }}" >> $GITHUB_ENV
    
    - name: Build
      run: |
        docker build --tag "$FRONTEND_IMAGE_WITH_TAG" --build-arg REACT_APP_NAMESPACE=default ./project-frontend
        docker build --tag "$IMAGES_IMAGE_WITH_TAG" ./project-images
        docker build --tag "$TODOS_IMAGE_WITH_TAG" ./project-todos
        docker build --tag "$BROADCASTER_IMAGE_WITH_TAG" ./project-broadcaster

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Publish
      run: |-
        docker push "$FRONTEND_IMAGE_WITH_TAG"
        docker push "$IMAGES_IMAGE_WITH_TAG"
        docker push "$TODOS_IMAGE_WITH_TAG"
        docker push "$BROADCASTER_IMAGE_WITH_TAG"
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      run: |-
        ./kustomize edit set image PROJECT/FRONTEND_IMAGE=volepp/$FRONTEND_IMAGE:${{ github.sha }}
        ./kustomize edit set image PROJECT/IMAGES_IMAGE=volepp/$IMAGES_IMAGE:${{ github.sha }}
        ./kustomize edit set image PROJECT/TODOS_IMAGE=volepp/$TODOS_IMAGE:${{ github.sha }}
        ./kustomize edit set image PROJECT/BROADCASTER_IMAGE=volepp/$BROADCASTER_IMAGE:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'kustomization.yaml'
        message: New version release for project application ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}