name: Release project application

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  FRONTEND_IMAGE: dwk-project-frontend
  IMAGES_IMAGE: dwk-project-images
  TODOS_IMAGE: dwk-project-todos

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create images' names and tags
      run: |
        echo "FRONTEND_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "IMAGES_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGES_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "TODOS_IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$TODOS_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: gcloud --quiet auth configure-docker

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build
      run: |
        docker build --tag "$FRONTEND_IMAGE_WITH_TAG" ./project-frontend
        docker build --tag "$IMAGES_IMAGE_WITH_TAG" ./project-images
        docker build --tag "$TODOS_IMAGE_WITH_TAG" ./project-todos
        
    - name: Publish
      run: |
        docker push "$FRONTEND_IMAGE_WITH_TAG"
        docker push "$IMAGES_IMAGE_WITH_TAG"
        docker push "$TODOS_IMAGE_WITH_TAG"

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy
      run: |-
        kubectl create namespace ${GITHUB_REF#refs/heads/} || true
        kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}
        ./kustomize edit set namespace ${GITHUB_REF#refs/heads/}
        ./kustomize edit set image PROJECT/FRONTEND_IMAGE=$FRONTEND_IMAGE_WITH_TAG
        ./kustomize edit set image PROJECT/IMAGES_IMAGE=$IMAGES_IMAGE_WITH_TAG
        ./kustomize edit set image PROJECT/TODOS_IMAGE=$TODOS_IMAGE_WITH_TAG
        kubectl create secret generic dwk-postgres-credentials --from-literal='POSTGRES_DB=${{ secrets.POSTGRES_DB }}'' --from-literal='POSTGRES_USER=${{ secrets.POSTGRES_USER }}'' --from-literal='POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}''
        kubectl apply -k .
        kubectl rollout status deployment $FRONTEND_IMAGE-dep
        kubectl rollout status deployment $IMAGES_IMAGE-dep
        kubectl rollout status deployment $TODOS_IMAGE-dep